//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THCard.AccountManagement.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountPassword
    {
        public System.Guid AccountId { get; set; }
        public string PasswordHash { get; set; }
        public string Salt { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
